server:
  #端口号
  port: 8888
spring:
  rabbitmq:
    local_domain:
      host: 10.25.8.115
      port: 5672
      username: sdt
      password: sdt108
      queue:  domain_115_upto_domain_132
      virtual-host: /domainExchange
    remote_domain:
      host: 10.26.14.132
      port: 5672
      username: sdt
      password: sdt108
      queue: domain_132_downto_115
      virtual-host: /domainExchange
