server:
  #端口号
  port: 8888
spring:
  rabbitmq:
    local_domain:
      host: 10.25.8.115
      port: 5672
      username: sdt
      password: sdt108
      queue:  domain_115_to_domain_155
      avail-dst-domain: domain_155
      self-domain: domain_115
      virtual-host: /domainExchange
    remote_domain:
      host: 10.26.8.155
      port: 5672
      username: sdt
      password: sdt108
      queue: domain_155_to_domain_115
      virtual-host: /domainExchange
