server:
  #端口号
  port: 8888
spring:
  rabbitmq:
    local_domain:
      host: 10.25.8.115
      port: 5672
      username: sdt
      password: sdt108
      queue:  domain_115_to_domain_132
      avail-dst-domain: domain_132
      self-domain: domain_115
      virtual-host: /domainExchange
    remote_domain:
      host: 10.26.14.132
      port: 5672
      username: sdt
      password: sdt108
      queue: domain_132_to_domain_115
      virtual-host: /domainExchange
